# Generated by Django 5.2.14 on 2026-06-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='size_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
