# Generated by Django 5.2.14 on 2026-06-22 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio', '0002_audiofile_size_bytes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('*', '*'), ('#', '#')], help_text='Digit the caller presses to reach this menu from its parent.', max_length=1, null=True)),
                ('name', models.CharField(max_length=100)),
                ('menu_type', models.CharField(choices=[('playback', 'Playback only'), ('playback_record', 'Playback & record message'), ('dial_out', 'Dial out / forward')], default='playback', max_length=20)),
                ('dial_out_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('greeting', models.ForeignKey(blank=True, help_text='Audio played when the caller enters this menu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_menus', to='audio.audiofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ivr.menu')),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('parent', 'key'), name='unique_key_per_parent')],
            },
        ),
    ]
